baseURL: https://blog.damirhadzagic.com
languageCode: en-us
title: Damir's Blog
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Hello!"
    Content: Welcome to my blog. Here I will write tech related blogs whenever some idea pops into my head.
  socialIcons:
    - name: github
      url: "https://github.com/XiovV"
    - name: linkedin
      url: "https://www.linkedin.com/in/damirhadzagic/"

  ShowReadingTime: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

    