site_name: Gopher's Burrow
theme:
  name: material

  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
 
nav:
  - About me: index.md

  - DevOps:
     - Deploying Docker Containers with HashiCorp Nomad and Traefik: devops/nomad/nomad_tutorial.md
  
  - Binary Exploatation:
     - Buffer Overflow*: binary_exploatation/buffer_overflow.md

  - Game Hacking:
      - Introduction*: binary_exploatation/buffer_overflow
      - Getting a handle to a process*: binary_exploatation/buffer_overflow
      - Reading memory*: binary_exploatation/buffer_overflow
      - Writing memory*: binary_exploatation/buffer_overflow
