site_name: Gopher's Burrow
theme:
  name: material

  features:
    - navigation.sections
    - content.code.copy

  palette: 

    # Palette toggle for dark mode
    - scheme: slate

      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
 
nav:
  - About me: index.md

  - DevOps:
     - Deploying Docker Containers with HashiCorp Nomad and Traefik: devops/nomad/nomad_tutorial.md
  
  - Binary Exploatation:
     - Buffer Overflow*: binary_exploatation/buffer_overflow.md

  - Game Hacking:
      - Introduction: game_hacking/introduction
      - Cheat Engine*:
          - Scanning for values*: binary_exploatation/buffer_overflow
          - Defeating DMA*: binary_exploatation/buffer_overflow
      - External Cheats*:
          - Getting a handle to a process*: binary_exploatation/buffer_overflow
          - Reading memory*: binary_exploatation/buffer_overflow
          - Writing memory*: binary_exploatation/buffer_overflow
      - Internal Cheats*:
          - Writing our own DLL*: binary_exploatation/buffer_overflow
          - DLL Injection*: binary_exploatation/buffer_overflow
          - Reading memory*: binary_exploatation/buffer_overflow
          - Writing memory*: binary_exploatation/buffer_overflow

